version: 2
jobs:
  build:
    docker:
      - image: docker:19.03.4

    working_directory: ~/app

    steps:
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}

      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t hoal/access-python:3.7 .

      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push hoal/access-python:3.7

workflows:
  version: 2
  build_image_and_push_to_registry:
    jobs:
      - build:
          context: Access
